### ISSUE TITLE
Sabbir has not made any contributions yet

### ISSUE THREAD

**Issue by azikram** [Shahriar-exoldius/GitTutorial#4]
...that is why he's not shown in the **Contributors** column.

![Contributions that are counted, GitHub](https://i.postimg.cc/FKyBpLMb/2020-10-28-15-10-08.png)

For more, click [here](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile).

**Comment by Shahriar-exoldius** [comment]
What did he violate?!
